# Generated by Django 4.2.5 on 2023-09-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_coursedelivery_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedelivery',
            name='course',
            field=models.CharField(max_length=255),
        ),
    ]
